const fs = require('fs');

let content = fs.readFileSync('electron/main.ts', 'utf-8');

// Find the startBackend function
const funcStart = content.indexOf('async function startBackend()');
const funcEnd = content.indexOf('// ============================================================\n// 窗口');
const oldFunc = content.slice(funcStart, funcEnd);

const newFunc = [
'async function startBackend(): Promise<void> {',
'  // 确保 userData/.env 存在(.env.example 复制过去)',
'  const userData = app.getPath(\'userData\');',
'  const userEnv = path.join(userData, \'.env\');',
'  if (!existsSync(userEnv)) {',
'    try {',
'      const examplePath = isDev',
'        ? path.resolve(__dirname, \'..\', \'.env.example\')',
'        : path.join(__dirname, \'..\', \'.env.example\');',
'      if (existsSync(examplePath)) {',
'        copyFileSync(examplePath, userEnv);',
'        log.info(\'[Setup] 已初始化 \' + userEnv);',
'        generateJwtSecretIfDefault(userEnv);',
'      } else {',
'        log.warn(\'[Setup] 找不到 .env.example: \' + examplePath);',
'      }',
'    } catch (e) {',
'      log.warn(\'[Setup] 复制 .env.example 失败:\', e);',
'    }',
'  } else {',
'    generateJwtSecretIfDefault(userEnv);',
'  }',
'',
'  if (isDev) {',
'    // 开发:spawn 子进程,用 tsx 加载器',
'    return new Promise((resolve) => {',
'      const nodePath = process.execPath;',
'      const tsxLoader = path.resolve(__dirname, \'..\', \'node_modules\', \'tsx\', \'dist\', \'cli.mjs\');',
'      const backendEntry = path.resolve(__dirname, \'..\', \'api\', \'server.ts\');',
'      const args = [',
'        \'--import\', \'tsx/esm\',',
'        backendEntry,',
'        \'--no-deprecation\',',
'      ];',
'      const cwd = path.resolve(__dirname, \'..\');',
'',
'      log.info(\'[Backend] 启动: \' + nodePath + \' \' + args.join(\' \') + \' (cwd=\' + cwd + \')\');',
'',
'      const env = {',
'        ...process.env,',
'        PORT: String(BACKEND_PORT),',
'        NODE_ENV: \'development\',',
'        XIAOHONGYI_USER_DATA: app.getPath(\'userData\'),',
'        ELECTRON_RUN_AS_NODE: \'1\',',
'      };',
'',
'      backendProcess = spawn(nodePath, args, {',
'        stdio: [\'ignore\', \'pipe\', \'pipe\'],',
'        env,',
'        cwd,',
'      });',
'',
'      backendProcess.stdout?.on(\'data\', (data: Buffer) => {',
'        const s = data.toString();',
'        log.info(\'[Backend] \' + s.trim());',
'        if (!backendReady && (s.includes(\'Server ready\') || s.includes(\'listening\'))) {',
'          backendReady = true;',
'          resolve();',
'        }',
'      });',
'',
'      backendProcess.stderr?.on(\'data\', (data: Buffer) => {',
'        const s = data.toString();',
'        if (s.includes(\'DeprecationWarning\')) {',
'          log.debug(\'[Backend] \' + s.trim());',
'        } else {',
'          log.warn(\'[Backend] \' + s.trim());',
'        }',
'        if (!backendReady && (s.includes(\'Server ready\') || s.includes(\'listening\'))) {',
'          backendReady = true;',
'          resolve();',
'        }',
'      });',
'',
'      backendProcess.on(\'exit\', (code, signal) => {',
'        const msg = \'后端进程退出 code=\' + code + \' signal=\' + signal;',
'        log.error(\'[Backend] \' + msg);',
'        backendProcess = null;',
'        backendReady = false;',
'        if (!isQuitting) {',
'          backendCrashed = true;',
'          if (mainWindow) {',
'            dialog.showErrorBox(\'后端服务异常\', msg + \'\\n请重启应用或联系开发者。\');',
'            app.quit();',
'          }',
'        }',
'      });',
'',
'      backendProcess.on(\'error\', (err) => {',
'        log.error(\'[Backend] spawn error:\', err);',
'      });',
'',
'      setTimeout(() => {',
'        if (!backendReady) {',
'          log.warn(\'[Backend] 启动超时(15s),继续加载窗口\');',
'          resolve();',
'        }',
'      }, 15000);',
'    });',
'  }',
'',
'  // 生产:直接在主进程中 import 后端代码(主进程有 asar 集成)',
'  log.info(\'[Backend] 在主进程中加载后端...\');',
'  try {',
'    const backendEntry = path.join(process.resourcesPath, \'api-dist\', \'server.mjs\');',
'    process.env.PORT = String(BACKEND_PORT);',
'    process.env.NODE_ENV = \'production\';',
'    process.env.XIAOHONGYI_USER_DATA = app.getPath(\'userData\');',
'',
'    await import(backendEntry);',
'    backendReady = true;',
'    backendProcess = null;',
'    log.info(\'[Backend] 后端就绪\');',
'  } catch (e) {',
'    const msg = \'后端加载失败: \' + (e instanceof Error ? e.message : String(e));',
'    log.error(\'[Backend] \' + msg);',
'    backendCrashed = true;',
'    if (mainWindow) {',
'      dialog.showErrorBox(\'后端服务异常\', msg + \'\\n请重启应用或联系开发者。\');',
'      app.quit();',
'    }',
'  }',
'}',
'',
].join('\n');

content = content.replace(oldFunc, newFunc);
fs.writeFileSync('electron/main.ts', content, 'utf-8');
console.log('OK: replaced startBackend function');